name: Integration tests

on:
  push:
    branches:
      - "master"
      - "release*"

permissions:
  id-token: write
  contents: read

jobs:
  integration-test:
    runs-on: ubuntu-latest
    env:
      CLUSTER_NAME: vpc-rc-ci-test
      K8S_VERSION: 1.23
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v3
      - name: Set up Docker QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - name: Set up tools
        run: |
          go install -mod=mod github.com/onsi/ginkgo/v2/ginkgo@latest
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin/
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.OSS_TEST_ROLE_ARN }}
          role-duration-seconds: 7200
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Create EKS Cluster
        run: |
          ./scripts/test/create-cluster.sh \
            -n $CLUSTER_NAME \
            -v $K8S_VERSION \
            -s $GITHUB_RUN_NUMBER
      - name: Create IAM Roles
        run: |
          ./scripts/test/iam-resources.sh \
            -n $CLUSTER_NAME \
            -s $GITHUB_RUN_NUMBER \
            -o "create"
      - name: Run integration tests
        run: |
          ./scripts/test/test-with-eksctl.sh \
            -n $CLUSTER_NAME \
            -s $GITHUB_RUN_NUMBER
      - name: Delete IAM Roles
        if: always()
        run: |
          ./scripts/test/iam-resources.sh \
            -n $CLUSTER_NAME \
            -s $GITHUB_RUN_NUMBER \
            -o "delete"
      - name: Delete EKS Cluster
        if: always()
        run: |
          ./scripts/test/delete-cluster.sh
